services:
  redis:
    image: redis:latest
    container_name: redis_container
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis_gui_container
    ports:
      - "5540:5540"
volumes:
  mysql_data:
  redis_data:

